### ISSUE TITLE
futures 3.0 port or removal

### ISSUE THREAD

**Issue by tamasblummer** [rust-bitcoin/murmel#22]
this project uses futures 2 (in p2p.rs and constructor.rs) which was yanked without notice, hence currently using a private copy. Features of futures 1 are not sufficient and 3 is not yet released. Wait for futures 3 and port or replace futures use with something else.

**Comment by TigerInYourDream** [comment]
> this project uses futures 2 (in p2p.rs and constructor.rs) which was yanked without notice, hence currently using a private copy. Features of futures 1 are not sufficient and 3 is not yet released. Wait for futures 3 and port or replace futures use with something else.

Hi, when will it work?

**Comment by tamasblummer** [comment]
I am currently building a product using it and hope to get it stabilized within a Month. The futures stuff depends on Rust.

**Comment by tamasblummer** [comment]
moved to futures 3.0
