### ISSUE TITLE
can't build master

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/murmel#24]
bab615558fcf296f95b1f2d7aec867e86fdd0663

$ cargo build --release
   Compiling libsqlite3-sys v0.9.3
   Compiling hammersbald v1.6.0
error[E0463]: can't find crate for `bitcoin_hashes`
  --> /home/casatta/.cargo/registry/src/github.com-1ecc6299db9ec823/hammersbald-1.6.0/src/lib.rs:32:1
   |
32 | extern crate bitcoin_hashes;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `hammersbald`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by tamasblummer** [comment]
lightning finally upgraded to bitcoin 0.18, now I can clean up.

**Comment by tamasblummer** [comment]
resolved
